CREATE TABLE channels (
	id INT AUTO_INCREMENT PRIMARY KEY,
	y_id VARCHAR(255) DEFAULT NULL,
	title VARCHAR(255) DEFAULT NULL,
	thumbnail VARCHAR(255) DEFAULT NULL,
	description TEXT DEFAULT NULL,
	published_at TIMESTAMP,  -- when the channel was created on youtube 
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT UC_Y_ID UNIQUE (y_id)
);

CREATE TABLE categories (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT UC_CategoryTitle UNIQUE (title)
);

CREATE TABLE categoriesMatcher (
	id INT AUTO_INCREMENT PRIMARY KEY,
	channel_id INT NOT NULL,
	category_id INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FK_ChannelCategoryMatcher FOREIGN KEY (`channel_id`) REFERENCES `channels`(`id`) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FK_CategoryChannelMatcher FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON UPDATE CASCADE ON DELETE CASCADE
);

